mitodl/mitxpro-theme

- lms/templates/header/user_dropdown.html
Fixes https://github.com/mitodl/mitxpro/issues/582
**How this should be tested:**
- [Apply theme](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/changing_appearance/theming/enable_themes.html), and visit dashboard.
- Set `XPRO_BASE_URL` in settings
- You should see above changes.
**Screenshot(s):**
> changes made to user dropdown

- .gitignore
- lms/static/templates
- lms/templates/header/navbar-not-authenticated.html
This PR removes the `Sign In` and `Register` links from the navigation bar at the top which appears for non-authenticated users. This impacts the intermediate logout view from OpenEdX to xPRO redirection where previously these buttons were visible while OpenEdX was redirecting the user to xPRO after a logout.
Screenshot:
> #654 Remove sign in/register buttons from logout view

- lms/templates/header/user_dropdown.html
**Relevant tickets:**
Fixes https://github.com/mitodl/mitxpro/issues/582
Show user's name from UserProfile in the navbar.
**How to test it manually?**
Make sure you have `name` in user's profile object.
Visit dashboard.
> fix user's name in navbar

- lms/templates/footer.html
Updates footer links in template in accordance to https://github.com/mitodl/mitxpro/issues/820
- `ENABLE_MKTG_SITE` should be set to `True`
- `SUPPORT_SITE_LINK` should be set to `https://xpro.zendesk.com/hc/`
- `CONTACT` (inside `MKTG_URLS`) should have the absolute URL: `https://xpro.zendesk.com/hc/en-us/requests/new`
- `BLOG`, `ENTERPRISE`, `DONATE` etc. (keys for links that we don't want) should not exist in `MKTG_URLS`
Screenshot
> #820 OpenEdx Theme Footer Links

- cms/templates/404.html
- lms/templates/static_templates/404.html
**Relevant tickets:**
Fixes https://github.com/mitodl/mitxpro/issues/819
Update 404 pages in CMS and LMS
**How to test it manually?**
- Make sure you have `XPRO_BASE_URL="http://xpro.odl.local:8053/"` and `TECH_SUPPORT_EMAIL="MIT xPRO <xpro@mit.edu>"` in settings
- Visit any page which doesn't exists. :)
**Screenshot:**
**LMS**
> update 404 page

- cms/templates/widgets/user_dropdown.html
**Relevant ticket:**
Fixes https://github.com/mitodl/mitxpro/issues/942
Override `cms/templates/widgets/user_dropdown.html` to show user's full name in studio header.
**How to test it manually?**
- Make sure you have `name` set against your user.
- Visit studio, you should see full name in header.
**Screenshot(if applicable)**
> display user's full name in studio header

- lms/templates/header/navbar-authenticated.html
**Relevant tickets:**
Fixes https://github.com/mitodl/mitxpro/issues/941
override template to replace discover new with catalog and link it to xPROro catalog
**How to test it manually?**
Visit any course page on LMS, you should see catalog with link to xPro catalog.
**Screenshot(if applicable)**
> replace discover new with catalog and link it to xPRO catalog

- lms/templates/footer.html
As per conversation over [ISSUE-1015](https://github.com/mitodl/mitxpro/issues/1015), We used the Django base settings to build the footer URL's.
> Used the django base settings

- lms/templates/dashboard.html
- lms/templates/footer.html
- lms/templates/header/navbar-authenticated.html
- lms/templates/header/user_dropdown.html
The urlparse in Python 2.7 was renamed to urllib.parse in Python 3. This PR addresses that change
> Changed to urllib.parse for python3

- lms/templates/footer.html
With juniper when logging in to the xpro sandbox, I was coming across the browser warning below:
After looking around and testing manually on the sandbox, it appeared that when loading the logo in the footer, it was hitting the `else` condition over [here](https://github.com/edx/edx-platform/blob/open-release/juniper.master/lms/djangoapps/branding/api.py#L497). I tested the change in this PR manually on the sandbox, and it appeared to solve the issue.
> Fix footer logo to use https

- lms/templates/header/navbar-authenticated.html
fixes: #27 
Shoppingcart has been almost deprecated for quite some time so it make sense to remove the shopping cart reference from this theme repo.
Installed the mitxpro-theme repo with edx-platform master and open any course.
further reference: https://github.com/edx/edx-platform/pull/23970
> Removed shopping cart reference from header

- lms/templates/dashboard.html
https://github.com/mitodl/mitxpro-theme/issues/31
With edx's master (koa), mitxpro-theme breaks at /dashboard if the user has any enrolled course.
There are two approaches to get this issue fixed.
1) Rebasing dashboard with edx's master (koa) dashboard.
2) Pick the variable which causes the issue and add it to the mako template.
I have used the first approach to update the whole dashboard.html, because I think it's better to keep things updated as much as we can.
https://github.com/mitodl/mitxpro-theme/pull/24/files
Before:
After:
> rebasing dashboard with edx koa

- README.md
fixes #26 
This PR adds any additional or updated steps to set up the theme with the `edx-platform` master. 
With the release of **`Juniper`** and the upcoming **`Koa`** there were some changes related to how we set configurations for our themes e.g. moving from `json` to `yml` files.
> Updated readme and added steps for setting up theme

- lms/templates/support/contact_us.html
Closes #33 
This PR overrides the contact Us page in our xPRO theme.
**Testing Instructions:**
- On your LMS go to `/support/contact_us`
- Verify that you see two links as mentioned in the associated ticket instead of Open edX's default contact Us page.
**Screenshots:**
> Override contact us page

- lms/templates/support/contact_us.html
This is a reapplication of PR #34 on the koa branch
Closes #33 
This PR overrides the contact Us page in our xPRO theme.
**Testing Instructions:**
- On your LMS go to `/support/contact_us`
- Verify that you see two links as mentioned in the associated ticket instead of Open edX's default contact Us page.
**Screenshots:**
> Koa: Override contact us page

- lms/templates/ace_common/edx_ace/common/base_body.html
https://github.com/mitodl/mitxpro/issues/1695
Replaces edX's logo with xPro's logo in email templates
- Setup edx devstack
- Enable mitxpro-theme
- Configure emailing credentails
- Enroll a student using instructors tab
In-case you fail to configure email (like me), then you can simply do the following:
- Enter LMS shell (make lms-shell)
- Go to Ace Messages filebase (cd /edx/src/ace_messages)
- You can see new `.timestamp.html` files having the whole email context.
Before:
After:
> replacing edx's logo with xpro's logo in email template

- lms/templates/footer.html
Fixes https://github.com/mitodl/hq/issues/759 & https://github.com/mitodl/hq/issues/631
Updates the title for the Accessibility link in the footer. The default edX title is `Accessibility Policy` but we require `Accessibility`.
- Follow the readme to integrate the footer.
- Add the following settings in your `private.py`
```
SUPPORT_SITE_LINK = "https://xpro.zendesk.com/hc"
MKTG_URL_LINK_MAP = {
"ABOUT": "about",
"PRIVACY": "privacy",
"TOS": "tos",
"HONOR": "honor",
"ACCESSIBILITY": "accessibility_policy",
"HELP_CENTER": "help-center"
}
MKTG_URL_OVERRIDES = {
"PRIVACY": "https://rc.xpro.mit.edu/privacy-policy/",
"TOS": "https://rc.xpro.mit.edu/terms-of-service/",
"ABOUT": "https://rc.xpro.mit.edu/about-us/",
"HONOR": "https://rc.xpro.mit.edu/honor-code/",
"ACCESSIBILITY": …
```
> feat(footer): update accessibility link title

- lms/templates/instructor/instructor_dashboard_2/membership.html
https://github.com/mitodl/hq/issues/2378
- Instructors must not have the ability to manually enroll users through the instructor dashboard in open edX.
- To ensure consistency, all enrollments should be performed exclusively within the MITx Pro itself.
- Setup the theme
- As an Instructor (not an admin), add a course in the `studio`.
- Go to the instructor dashboard.
- Click on the `Membership` tab on either the instructor's tab/page or the instructor dashboard.
- Check if there's an `Enrollment Section`. It shouldn't be there for the Instructor.
- Now, try the same steps but as an admin user.
- Confirm that the `Enrollment Section` is available for admin users.
**For Admin/superuser:**
**Instructors**
> fix: Block Manual Enrollment of learners in open edX

- lms/templates/instructor/instructor_dashboard_2/membership.html
https://github.com/mitodl/hq/issues/2378
- Instructors must not have the ability to manually enroll users through the instructor dashboard in open edX.
- To ensure consistency, all enrollments should be performed exclusively within the MITx Pro itself.
- Setup the theme
- As an Instructor (not an admin), add a course in the `studio`.
- Go to the instructor dashboard.
- Click on the `Membership` tab on either the instructor's tab/page or the instructor dashboard.
- Check if there's an `Enrollment Section`. It shouldn't be there for the Instructor.
- Now, try the same steps but as an admin user.
- Confirm that the `Enrollment Section` is available for admin users.
**For Admin/superuser:**
**Instructors**
> fix: Block Manual Enrollment of learners in open edX (#48)

- cms/templates/404.html
- lms/templates/footer.html
- lms/templates/static_templates/404.html
Partially related to https://github.com/mitodl/hq/issues/3094. 
Currently, Our themes use the `CONTACT` URL directly from `MKTG_URLS` dictionary in the settings. This was fine until there were no `MKTG_URL_OVERRIDES`. So, It's possible that a URL exists in `MKTG_URLS` but has been overridden in `MKTG_URL_OVERRIDES` but our theme would never pick it. The open edX helper method takes care of that e.g. it picks the URL from Django admin otherwise `MKTG_URL_OVERRIDES` otherwise `MKTG_URLS` which makes it flexible for us and consistent overall.
This PR makes our theme use the open edX helper method to get the marketing URLs from the appropriate place.
**Locally:**
- Set DEBUG=False in your private.py or yml
- Apply this theme and open any nonexistent page e.g. localhost:18000/abcd
- Now, See …
> fix: use marketing_link helper instead of MKTG_URLS for CONTACT

- cms/templates/404.html
- lms/templates/footer.html
- lms/templates/static_templates/404.html
backport of https://github.com/mitodl/mitxpro-theme/pull/56 for the `Quince` branch.
> fix: use marketing_link helper instead of MKTG_URLS for CONTACT (#56)

- lms/templates/ace_common/edx_ace/common/base_body.html
None
When we migrated towards using the new logo in xPRO we added the rc logo in the email for testing. But we are using the email template from Django admin so we can change the logo URL from there whenever we need to. So, I'm doing two things in this PR
- Change the default logo to be a PNG instead of SVG because email doesn't support SVG logo
- Change the RC URL to production URL
> style: shift back to use logo from production

- lms/templates/ace_common/edx_ace/common/base_body.html
None, Backports https://github.com/mitodl/mitxpro-theme/pull/61 to quince
> style: backport email logo 

- lms/templates/header/navbar-authenticated.html
#45 
- Removed the unused tabs, e.g. `Profile` and `Journals`
- Open edX has removed these from their upstream themes as well so we should remove these too, Removing these would make the theme less breakable with ongoing changes in edX.
- Should be tested both on `master` and `olive` branch of edX
- Once your edX instance is setup, Follow the instructions in the `readme` of this repo and setup theme on this branch, nothing should break
- A smoke test is good
> fix: remove unused Journals and Profile tabs
